const MIN_PASSWORD_LENGTH = 8
const SMS_CODE_LENGTH = 6
const SMS_CODE_TTL = 30 * 1000
const SAFE_CAPTCHA_SCORE = 0.5
const LOCK_TIMEOUT = 5

module.exports = {
    MIN_PASSWORD_LENGTH,
    SMS_CODE_LENGTH,
    SMS_CODE_TTL,
    LOCK_TIMEOUT,
    SAFE_CAPTCHA_SCORE,
}
